const productos = [
  {Nombre:"Bandeja 15*15",Descripcion:"Sirviendo tus mejores momentos en familia",Precio:1460,ID:"Cod: 29",Diseños:3,Categoría:"HOGAR",img:"./assets/Decorativo.jpg"},
{Nombre:"Bandeja Cónica Nro 1 - 20X20",Descripcion:"Sirviendo tus mejores momentos en familia",Precio:350,ID:"Cod: 18",Diseños:1,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Bandeja Cónica Rectangular - 35X40",Descripcion:"Sirviendo tus mejores momentos en familia",Precio:400,ID:"Cod: 19",Diseños:4,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Bandeja Cónica Nro 2 - 25X25",Descripcion:"Sirviendo tus mejores momentos en familia",Precio:370,ID:"Cod: 20",Diseños:2,Categoría:"HOGAR",img:"./assets/Decorativo.jpg"},
{Nombre:"Bandeja 20X40",Descripcion:"Sirviendo tus mejores momentos en familia",Precio:370,ID:"Cod: 23",Diseños:1,Categoría:"HOGAR",img:"./assets/Decorativo.jpg"},
{Nombre:"Bandeja Cónica Nro 5 - 30X30",Descripcion:"Tus mejores momentos en familia",Precio:430,ID:"Cod: 21",Diseños:1,Categoría:"HOGAR",img:"./assets/Decorativo.jpg"},
{Nombre:"Bandeja 15X30",Descripcion:"Tus mejores momentos en familia",Precio:330,ID:"Cod: 22",Diseños:3,Categoría:"HOGAR",img:"./assets/Decorativo.jpg"},
{Nombre:"Tabla Ovalada",Descripcion:"Tus mejores momentos en familia",Precio:350,ID:"Cod: 102",Diseños:1,Categoría:"HOGAR",img:"./assets/Decorativo.jpg"},
{Nombre:"Bandeja Rústica",Descripcion:"Tus mejores momentos en familia",Precio:600,ID:"Cod: 25",Diseños:2,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Paleta Madera",Descripcion:"Tus mejores momentos en familia",Precio:270,ID:"Cod: 100",Diseños:3,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Tabla 25X25",Descripcion:"Tus mejores momentos en familia",Precio:350,ID:"Cod: 24",Diseños:6,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Cajón Doble Porta Mate",Descripcion:"Cajón doble con manijas",Precio:500,ID:"Cod: 124",Diseños:1,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Juego De Cubiertos",Descripcion:"Juego de cubiertos fabricados y pintados con mucho amor",Precio:2500,ID:"Cod: 57",Diseños:4,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Mesa Redonda",Descripcion:"Mesa redonda",Precio:1100,ID:"Cod: 91",Diseños:1,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Galletitero No.1 - 12X17",Descripcion:"Fibrofacil",Precio:490,ID:"Cod: 44",Diseños:1,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Galletitero No.2 - 15X20",Descripcion:"Fibrofacil",Precio:530,ID:"Cod: 45",Diseños:2,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Panera",Descripcion:"Panera pintada",Precio:350,ID:"Cod: 46",Diseños:1,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Caja Galletitas 20X20",Descripcion:"Fibrofacil",Precio:600,ID:"Cod: 92",Diseños:3,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Cesta Tela Con Manija Grande",Descripcion:"Cesta de tela con manijas",Precio:350,ID:"Cod: 73",Diseños:1,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Cesta Tela Con Manija Chica",Descripcion:"Cesta de tela con manijas",Precio:280,ID:"Cod: 74",Diseños:1,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Cesta Tela Chica",Descripcion:"Cesta de tela chica sin manijas",Precio:200,ID:"Cod: 75",Diseños:4,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Cesta Tela Grande",Descripcion:"Cesta de tela chica sin manijas",Precio:280,ID:"Cod: 77",Diseños:3,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Maceta Nro 1 - 8X8",Descripcion:"Sentimientos para el hogar",Precio:160,ID:"Cod: 82",Diseños:2,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Maceta Nro 1 - 11X11",Descripcion:"Sentimientos para el hogar",Precio:230,ID:"Cod: 83",Diseños:2,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Mini Cajón - 10X15",Descripcion:"Sentimientos para el hogar",Precio:235,ID:"Cod: 84",Diseños:2,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Maceta Muelita - 20X20X17",Descripcion:"Sentimientos para el hogar",Precio:830,ID:"Cod: 95",Diseños:1,Categoría:"HOGAR",img:"./assets/Hogar.jpg"},
{Nombre:"Mini Cajón Multiusos - 10X10X18",Descripcion:"Cajón",Precio:250,ID:"Cod: 122",Diseños:2,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Cajón, Maceta Multiusos - 40X10X10",Descripcion:"Cajón",Precio:800,ID:"Cod: 121",Diseños:1,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Caja De Té 3 Divisiones",Descripcion:"3 Divisiones",Precio:550,ID:"Cod: 40",Diseños:1,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Caja De Té 4 Divisiones",Descripcion:"4 Divisiones",Precio:650,ID:"Cod: 41",Diseños:1,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Caja De Té 6 Divisiones",Descripcion:"6 Divisiones",Precio:800,ID:"Cod: 42",Diseños:1,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Mate Plástico Con Manija",Descripcion:"Incluye bombilla",Precio:400,ID:"Cod: 47",Diseños:2,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Mate Plástico Geométrico",Descripcion:"Incluye bombilla",Precio:400,ID:"Cod: 48",Diseños:4,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Mate De Madera Geométrico",Descripcion:"Incluye bombilla",Precio:700,ID:"Cod: 49",Diseños:10,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Mate De Madera Boca Redonda",Descripcion:"Incluye bombilla",Precio:570,ID:"Cod: 50",Diseños:13,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Mate De Vidrio",Descripcion:"Incluye bombilla",Precio:320,ID:"Cod: 51",Diseños:4,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Mate Vitrificado",Descripcion:"Incluye bombilla",Precio:780,ID:"Cod: 98",Diseños:4,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Set Matero Con Bandeja Cónica",Descripcion:"Coleccionando buenos momentos",Precio:1550,ID:"Cod: 26",Diseños:2,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Set Matero Con Bandeja Cónica Chica",Descripcion:"Coleccionando buenos momentos",Precio:850,ID:"Cod: 27",Diseños:3,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Set Matero Bandeja Recta",Descripcion:"Coleccionando buenos momentos",Precio:1460,ID:"Cod: 29",Diseños:1,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Set Matero Amigos",Descripcion:"Coleccionando buenos momentos",Precio:1300,ID:"Cod: 30",Diseños:2,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Set Matero Individual",Descripcion:"Coleccionando buenos momentos",Precio:650,ID:"Cod: 32",Diseños:2,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Set Matero Tabla Económica",Descripcion:"Coleccionando buenos momentos",Precio:500,ID:"Cod: 93",Diseños:3,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Set Matero Tabla - 25X25",Descripcion:"Mate geométrico boca ancha y bombilla.",Precio:1000,ID:"Cod: 31",Diseños:7,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Set Matero Cajón Doble",Descripcion:"2 mates con bombilla y cajón contenedor doble con manijas",Precio:1500,ID:"Cod: 123",Diseños:1,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Azucarera",Descripcion:"Azucarera pequeña",Precio:700,ID:"Cod: 97",Diseños:2,Categoría:"HOGAR",img:"./assets/Accesorio.jpg"},
{Nombre:"Base de velas 11x22",Descripcion:"Los precios no incluyen las velas",Precio:400,ID:"Cod: 58",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Base de velas 4 calados",Descripcion:"Los precios no incluyen las velas",Precio:1500,ID:"Cod: 59",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Base de velas 3 calados",Descripcion:"Los precios no incluyen las velas",Precio:800,ID:"Cod: 60",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Base de velas o maceta",Descripcion:"Los precios no incluyen las velas",Precio:780,ID:"Cod: 61",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Base de velas 20*12",Descripcion:"Los precios no incluyen las velas",Precio:850,ID:"Cod: 64",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Base de velas de chapa pergamino",Descripcion:"Los precios no incluyen las velas",Precio:1000,ID:"Cod: 62",Diseños:6,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Base de velas 14*14",Descripcion:"Los precios no incluyen las velas",Precio:340,ID:"Cod: 65",Diseños:4,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Base de velas yin-yang",Descripcion:"Los precios no incluyen las velas",Precio:600,ID:"Cod: 63",Diseños:4,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Base para velas 4 chapas curvas",Descripcion:"Base de madera con 4 chapas curvas, medida 38*10, no incluyen las velas",Precio:820,ID:"Cod: 66",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Base para vela rustica 3 agujeros",Descripcion:"Medidas 30x7x4 los precios no incluyen las velas",Precio:670,ID:"Cod: 94",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Tridimensional 23*28",Descripcion:"Cuadro en fibrofacil con profundidad y vidrio 23*28",Precio:670,ID:"Cod: 78",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Tridimensional 34*28",Descripcion:"Tridimensional 34*28",Precio:900,ID:"Cod: 79",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Cuadro cajón 10*15",Descripcion:"Cuadro cajón 10*15",Precio:370,ID:"Cod: 80",Diseños:3,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Cuadro cajón 30*40",Descripcion:"Cuadro cajón 30*40",Precio:720,ID:"Cod: 81",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Colgante 4 piezas",Descripcion:"Colgante 4 piezas en blanco y negro",Precio:250,ID:"Cod: 131",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Cuadros 4 piezas",Descripcion:"Cuatro cuadros de 15x15",Precio:400,ID:"Cod: 130",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Cuadro tablas",Descripcion:"Cuadro de apoye con frase",Precio:500,ID:"Cod: 129",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Portallaves",Descripcion:"Portallave",Precio:700,ID:"Cod: 56",Diseños:4,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Caja 10*10",Descripcion:"Caja 10*10",Precio:230,ID:"Cod: 33",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Cajón rectangular",Descripcion:"Cajón rectangular",Precio:470,ID:"Cod: 37",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Caja hexagonal no 2",Descripcion:"Caja hexagonal fibrofacil 22*7",Precio:400,ID:"Cod: 34",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Caja rectangular",Descripcion:"Caja rectangular",Precio:300,ID:"Cod: 35",Diseños:3,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Cajón pino",Descripcion:"Cajón pino",Precio:950,ID:"Cod: 38",Diseños:5,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Caja portabolsa",Descripcion:"Caja portabolsa",Precio:450,ID:"Cod: 36",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Cajonera 5 cajones",Descripcion:"Cajonera 5 cajones 40x13x13",Precio:1300,ID:"Cod: 125",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Caja hexagonal no1",Descripcion:"Caja hexagonal de fibrofacil 17*7",Precio:300,ID:"Cod: 104",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Caja con vidrio",Descripcion:"Caja con vidrio 25*20",Precio:700,ID:"Cod: 101",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Caja para alimento de mascotas",Descripcion:"Caja 17x17 con vidrio. ",Precio:500,ID:"Cod: 118",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Perchero 1 gancho",Descripcion:"Perchero 1 gancho",Precio:600,ID:"Cod: 52",Diseños:7,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Perchero 2 ganchos",Descripcion:"Perchero 2 ganchos",Precio:1600,ID:"Cod: 53",Diseños:5,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Perchero 3 ganchos",Descripcion:"Perchero 3 ganchos",Precio:1800,ID:"Cod: 54",Diseños:3,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Perchero 4 ganchos",Descripcion:"Perchero 4 ganchos",Precio:2000,ID:"Cod: 55",Diseños:17,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Perchero 4 ganchos",Descripcion:"Perchero 5 ganchos",Precio:2200,ID:"Cod: 128",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Perchero para correa 1 gancho",Descripcion:"Percheros personalizados para tu mascota.",Precio:500,ID:"Cod: 119",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Perchero para correa 2 ganchos",Descripcion:"Perchero personalizado para tus mascotas 2 ganchos.",Precio:700,ID:"Cod: 120",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón tejido 40*40",Descripcion:"Almohadón de lana, tejido a mano con relleno. Variedad de diseños.",Precio:850,ID:"Cod: 3",Diseños:4,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón tejido 20*40",Descripcion:"Almohadón de lana, tejido a mano con relleno. Variedad de diseños. 20*40",Precio:430,ID:"Cod: 4",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón arpillera 30*30",Descripcion:"Almohadón arpillera con relleno. Variedad de diseños.",Precio:450,ID:"Cod: 5",Diseños:3,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón de jeans 30*30",Descripcion:"Jeans combinado con tela. Almohadón relleno. 30 x30",Precio:550,ID:"Cod: 6",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón arpillera 40*40",Descripcion:"Arpillera con relleno 40x40",Precio:550,ID:"Cod: 8",Diseños:5,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón arpillera 20*40",Descripcion:"Almohadón de arpillera, con relleno. Variedad de diseños. 20x40",Precio:280,ID:"Cod: 7",Diseños:5,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón gabardina 30*30",Descripcion:"Almohadón de gabardina, con relleno. Variedad de diseños. 30 x 30",Precio:550,ID:"Cod: 10",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón lienzo 30*30",Descripcion:"Almohadón lienzo, con relleno. Variedad de diseños. 30x30",Precio:450,ID:"Cod: 94",Diseños:3,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón chenille 40*40",Descripcion:"Chenille 40x40 con relleno",Precio:900,ID:"Cod: 14",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón gabardina 40*40",Descripcion:"Gabardina de 40x40 con relleno",Precio:650,ID:"Cod: 11",Diseños:4,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón chenille 30*30",Descripcion:"Chenille 30x30 con relleno",Precio:700,ID:"Cod: 15",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón chenille 20*40",Descripcion:"Chenille 20x40 con relleno",Precio:450,ID:"Cod: 13",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón gabardina 20*40",Descripcion:"Almohadón gabardina, con relleno. 20x40",Precio:325,ID:"Cod: 12",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón corazón",Descripcion:"Almohadón tela peluche.",Precio:650,ID:"Cod: 16",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Almohadón tejido triangulo",Descripcion:"Almohadón de lana, tejido a mano con relleno.",Precio:650,ID:"Cod: 117",Diseños:3,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón tejido 40*40",Descripcion:"Tejido a mano",Precio:550,ID:"Cod: 105",Diseños:4,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón tejido 20*40",Descripcion:"Tejido a mano",Precio:330,ID:"Cod: 106",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón arpillera 30*30",Descripcion:"Arpillera 30*30",Precio:450,ID:"Cod: 5",Diseños:3,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón de jeans 30*30",Descripcion:"Jeans combinado con tela 30x30",Precio:400,ID:"Cod: 110",Diseños:2,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón arpillera 40*40",Descripcion:"Arpillera 40*40",Precio:400,ID:"Cod: 108",Diseños:4,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón arpillera 20*40",Descripcion:"Tejido a mano",Precio:180,ID:"Cod: 109",Diseños:4,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón gabardina 40*40",Descripcion:"Gabardina 40x40",Precio:450,ID:"Cod: 112",Diseños:3,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón lienzo 30*30",Descripcion:"Lienzo 30x30",Precio:300,ID:"Cod: 113",Diseños:3,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón chenille 40*40",Descripcion:"Chenille 40x40",Precio:700,ID:"Cod: 116",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón gabardina 30*30",Descripcion:"Gabardina 30x30",Precio:400,ID:"Cod: 111",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón chenille 30*30",Descripcion:"Chenille 30x30",Precio:550,ID:"Cod: 115",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Funda para almohadón chenille 20*40",Descripcion:"Chenille 20x40",Precio:350,ID:"Cod: 114",Diseños:1,Categoría:"Decoracion",img:"./assets/Decorativo.jpg"},
{Nombre:"Bufanda con bolsillo",Descripcion:"Abrazándote con amor. Bolsillo. Tejido a mano.",Precio:1000,ID:"Cod: 86",Diseños:4,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Bufanda pañuelo",Descripcion:"Abrazándote con amor. Pañuelo tejida a mano.",Precio:600,ID:"Cod: 87",Diseños:2,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Cuello",Descripcion:"Abrazándote con amor. Cuello tejida a mano.",Precio:750,ID:"Cod: 88",Diseños:12,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Cuello para niños",Descripcion:"Abrazándote con amor. Cuellito de lana para niños. Tejido a mano.",Precio:500,ID:"Cod: 89",Diseños:2,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Guantes",Descripcion:"Guantes tejidos a mano.",Precio:500,ID:"Cod: 90",Diseños:7,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Bandolera",Descripcion:"Bandolera",Precio:400,ID:"Cod: 67",Diseños:1,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Neceser",Descripcion:"Neceser",Precio:250,ID:"Cod: 68",Diseños:4,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Barbijo",Descripcion:"Barbijo",Precio:120,ID:"Cod: 69",Diseños:2,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Porta alcohol en gel",Descripcion:"Porta alcohol en gel",Precio:150,ID:"Cod: 70",Diseños:2,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Estuche para anteojos",Descripcion:"Estuche para anteojos",Precio:150,ID:"Cod: 71",Diseños:1,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Ta te ti alfombra",Descripcion:"Alfombra",Precio:700,ID:"Cod: 72",Diseños:1,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Triangulo de mano",Descripcion:"Cartera de mano",Precio:400,ID:"Cod: 103",Diseños:1,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Portapañuelo",Descripcion:"Portapañuelo",Precio:189,ID:"Cod: 39",Diseños:3,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Alhajero 2 cajones",Descripcion:"Atesora los regalos de tus seres queridos. Fibrofacil de 9mm.",Precio:800,ID:"Cod: 1",Diseños:2,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Alhajero 4 cajones",Descripcion:"Atesora los regalos de tus seres queridos. Fibrofacil de 9mm.",Precio:1500,ID:"Cod: 2",Diseños:1,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Calzador 38cm",Descripcion:"Calzador 38cm",Precio:470,ID:"Cod: 43",Diseños:3,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Porta celular de tela",Descripcion:"Porta celular de tela",Precio:150,ID:"Cod: 85",Diseños:3,Categoría:"Accesorios",img:"./assets/Accesorio.jpg"},
{Nombre:"Alfajores",Descripcion:"Contiene seis alfajores premium de alta calidad para endulzar un lindo momento compartido.",Precio:1000,ID:"Cod: XX",Diseños:6,Categoría:"Accesorios",img:"./assets/Premium.jpg"},
{Nombre:"Caja mate",Descripcion:"Esta caja contiene lo más importante, que es nuestra cultura. ",Precio:1000,ID:"Cod: XX",Diseños:1,Categoría:"Accesorios",img:"./assets/Premium.jpg"},
{Nombre:"Caja vino",Descripcion:"El complemento perfecto para una buena cena o festejo. ",Precio:1000,ID:"Cod: XX",Diseños:1,Categoría:"Accesorios",img:"./assets/Premium.jpg"},
{Nombre:"Caja vino con copa",Descripcion:"El complemento perfecto para una buena cena o festejo. Además, posee una copa.",Precio:1000,ID:"Cod: XX",Diseños:1,Categoría:"Accesorios",img:"./assets/Premium.jpg"},
]

console.log(productos);
